name = "MeshPlots"
uuid = "de9684d3-f81f-49d9-ae9e-c828b202dea9"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.1.9"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
Meshes = "0.30"
RecipesBase = "1.1"
Tables = "1.7"
julia = "1.6"
